services:
  database:
    image: mariadb:11
    container_name: warble-mariadb

    restart: unless-stopped

    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

    ports:
      - "127.0.0.1:3306:3306"

    volumes:
      - warble_mariadb_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  warble_mariadb_data:
